# Generated by Django 4.1 on 2022-08-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterBook',
            new_name='Book',
        ),
    ]
