# Generated by Django 4.1 on 2022-08-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_co_author_alter_book_date_devolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
