# Generated by Django 4.1 on 2022-08-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_category_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="rented",
            new_name="borrowed",
        ),
        migrations.RemoveField(
            model_name="book",
            name="date_devolution",
        ),
        migrations.RemoveField(
            model_name="book",
            name="date_rented",
        ),
        migrations.RemoveField(
            model_name="book",
            name="name_rented",
        ),
        migrations.RemoveField(
            model_name="book",
            name="time_duration",
        ),
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_borrowed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_borrowed", models.DateTimeField(blank=True, null=True)),
                ("date_devolution", models.DateTimeField(blank=True, null=True)),
                ("time_duration", models.DateField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="book.book"
                    ),
                ),
            ],
        ),
    ]
