# Generated by Django 4.1 on 2022-08-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0013_alter_borrowing_date_borrowed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="time_duration",
        ),
    ]
