# Generated by Django 4.1 on 2022-08-24 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_email_alter_user_name_and_more"),
        ("book", "0014_remove_borrowing_time_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Livro"},
        ),
        migrations.AlterModelOptions(
            name="borrowing",
            options={"verbose_name": "Empréstimo"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoria"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=50, verbose_name="Autor"),
        ),
        migrations.AlterField(
            model_name="book",
            name="borrowed",
            field=models.BooleanField(default=False, verbose_name="Emprestado"),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="book.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="co_author",
            field=models.CharField(blank=True, max_length=50, verbose_name="Co-autor"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="book",
            name="registration_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de cadastro"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.user",
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="book.book",
                verbose_name="Livro",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="date_borrowed",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de empéstimo"
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="date_devolution",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de devolução"
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="name_borrowed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.user",
                verbose_name="Usuário cadastrado",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="name_borrowed_anonymous",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Usuário anônimo"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.user",
                verbose_name="Usuário",
            ),
        ),
    ]
