# Generated by Django 4.1 on 2022-08-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0015_alter_book_options_alter_borrowing_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="name_borrowed",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="name_borrowed_anonymous",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="username",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Nome do Usuário"
            ),
            preserve_default=False,
        ),
    ]
