# Generated by Django 4.1 on 2022-09-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_email_alter_user_name_and_more"),
        ("book", "0017_alter_borrowing_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
                verbose_name="Usuário",
            ),
        ),
    ]
